version: "3.8"

networks:
  net-app:
    driver: bridge
  net-db:
    driver: bridge

services:
  app:
    build: ./app
    container_name: app
    restart: always
    depends_on:
      - back-end
    ports:
      - "80:80"
    volumes:
      - "./app/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - net-app

  back-end:
    container_name: back-end
    build: ./back-end
    ports:
      - "3333:3333"
    networks:
      - net-app
      - net-db
    env_file:
      - "variables.env"
    depends_on:
      - db

  db:
    restart: always
    container_name: mysql
    image: mysql/mysql-server:8.0.32
    ports:
      - "3336:3306"
    networks:
      - net-db
    env_file:
      - "variables.env"
    volumes:
      - ./data/db_data:/var/lib/mysql

